/** Suggestions de tâches rapides par agent : cas d'usage les plus fréquents. */
export const AGENT_SUGGESTIONS: Record<string, string[]> = {
  directeur: [
    "Que dois-je faire aujourd'hui en priorité ?",
    "Analyse la situation actuelle de mon entreprise",
    "Quelles sont mes actions les plus urgentes ?",
    "Résume ce qui s'est passé aujourd'hui",
    "Quels problèmes nécessitent mon attention ?",
    "Quelles opportunités dois-je exploiter ?",
    "Analyse mes performances récentes",
    "Que puis-je faire pour augmenter mon chiffre d'affaires ?",
    "Quels agents doivent travailler sur mes priorités ?",
    "Fais-moi un briefing complet de mon entreprise",
    "Quelles tâches sont bloquées ou en retard ?",
    "Résume les actions de mes agents IA",
    "Identifie les 3 priorités les plus importantes",
    "Crée un business plan",
    "Aide-moi à prendre une décision",
  ],
  commercial: [
    "Trouve-moi 50 entreprises intéressées par mon service",
    "Trouve des prospects dans une ville ou région",
    "Trouve des prospects similaires à mes meilleurs clients",
    "Analyse et qualifie mes prospects",
    "Enrichis ma base de prospects",
    "Score mes prospects selon leur potentiel",
    "Identifie les prospects les plus intéressants à contacter",
    "Trouve le meilleur angle commercial pour chaque prospect",
    "Génère un email personnalisé pour mes prospects",
    "Crée une séquence de prospection",
    "Relance mes prospects sans réponse",
    "Quels prospects dois-je relancer aujourd'hui ?",
    "Analyse mon pipeline commercial",
    "Compare mon offre avec mes concurrents",
    "Transforme mes prospects intéressés en opportunités",
  ],
  devis: [
    "Crée un devis pour un client",
    "Crée un devis à partir d'une réunion",
    "Analyse cet audio et prépare un devis",
    "Transforme ce résumé de réunion en devis",
    "Retrouve un devis existant",
    "Modifie mon devis",
    "Quels devis sont en attente de réponse ?",
    "Relance les devis sans réponse",
    "Envoie une demande de paiement",
    "Crée un échéancier de paiement",
    "Quels paiements sont en retard ?",
    "Relance les paiements en attente",
    "Génère la facture correspondante",
    "Retrouve une facture",
    "Transforme ce devis accepté en projet",
  ],
  clients: [
    "Analyse la fiche complète d'un client",
    "Résume l'historique de ce client",
    "Quels clients nécessitent une attention ?",
    "Quels clients sont les plus rentables ?",
    "Identifie les clients à risque",
    "Prépare une réponse à une demande client",
    "Analyse les demandes clients récentes",
    "Quels documents manquent pour ce client ?",
    "Analyse la satisfaction de mes clients",
    "Identifie des opportunités d'upsell",
    "Identifie des opportunités de cross-sell",
    "Quels clients dois-je recontacter ?",
    "Analyse mes avis Google et réponds aux nouveaux avis",
    "Analyse ma réputation en ligne",
    "Enrichis automatiquement mes fiches clients",
  ],
  relances: [
    "Quels prospects dois-je relancer aujourd'hui ?",
    "Relance les prospects sans réponse",
    "Quels devis arrivent bientôt à expiration ?",
    "Relance mes devis en attente",
    "Quels paiements sont en retard ?",
    "Prépare une relance de paiement",
    "Relance les clients qui n'ont pas répondu",
    "Identifie les conversations sans réponse",
    "Crée une séquence de relance",
    "Personnalise une relance pour ce prospect",
    "Quels contacts risquent d'être perdus ?",
    "Montre-moi toutes mes relances en attente",
    "Programme une relance automatique",
    "Analyse l'efficacité de mes relances",
    "Quelles relances dois-je prioriser ?",
  ],
  marketing: [
    "Crée une stratégie marketing pour mon offre",
    "Trouve-moi des idées de contenu",
    "Crée une publication pour mes réseaux sociaux",
    "Crée un carrousel Instagram",
    "Génère une image pour cette campagne",
    "Génère une vidéo marketing",
    "Crée un calendrier de contenu",
    "Transforme cette idée en plusieurs contenus",
    "Crée une campagne pour promouvoir mon service",
    "Écris une publicité pour mon offre",
    "Analyse les performances de mon contenu",
    "Optimise cette publication pour générer plus de leads",
    "Crée une séquence de contenu sur 30 jours",
    "Adapte ce contenu pour plusieurs plateformes",
    "Fais-moi une veille concurrentielle de mon secteur",
  ],
  rh: [
    "Ajoute une offre d'emploi",
    "Analyse cette offre d'emploi",
    "Ajoute et analyse un candidat",
    "Compare les candidats pour cette offre",
    "Classe mes candidats par pertinence",
    "Quels candidats dois-je retenir ?",
    "Identifie les compétences manquantes",
    "Propose un entretien à ce candidat",
    "Propose-moi 3 créneaux disponibles",
    "Génère le message d'invitation",
    "Suis les réponses des candidats",
    "Analyse l'audio d'un entretien",
    "Prépare la synthèse complète d'un candidat",
    "Compare les résultats des entretiens",
    "Aide-moi à prendre une décision finale",
  ],
  gestion: [
    "Fais-moi un résumé financier",
    "Combien ai-je encaissé ce mois-ci ?",
    "Quels paiements sont en attente ?",
    "Quels paiements sont en retard ?",
    "Analyse mon chiffre d'affaires",
    "Compare mes revenus avec la période précédente",
    "Quels clients me rapportent le plus ?",
    "Quels produits ou services sont les plus rentables ?",
    "Analyse mes dépenses",
    "Identifie les dépenses inhabituelles",
    "Prépare un résumé pour mon comptable",
    "Analyse ma trésorerie",
    "Quelles factures restent impayées ?",
    "Prévois mes encaissements à venir",
    "Quels sont mes principaux indicateurs financiers ?",
  ],
  analyse: [
    "Réalise une étude de marché",
    "Fais une analyse sectorielle",
    "Analyse un concurrent",
    "Compare mon offre avec mes concurrents",
    "Identifie des opportunités de marché",
    "Identifie les menaces",
    "Trouve des opportunités de croissance",
    "Analyse la rentabilité d'une idée",
    "Surveille mon secteur",
    "Fais-moi une veille concurrentielle",
    "Recherche les dernières actualités importantes",
    "Programme une veille hebdomadaire",
    "Crée un briefing de veille",
    "Analyse ce qui se dit sur mon entreprise",
    "Compare ma réputation avec celle de mes concurrents",
  ],
  projets: [
    "Que dois-je faire aujourd'hui ?",
    "Organise mes tâches par priorité",
    "Quelles tâches sont en retard ?",
    "Quelles tâches bloquent mes projets ?",
    "Crée un plan de travail pour aujourd'hui",
    "Planifie ma semaine",
    "Transforme cette demande en tâches",
    "Analyse ma charge de travail",
    "Quelles tâches puis-je déléguer ?",
    "Quels projets prennent du retard ?",
    "Crée une checklist pour ce projet",
    "Fais un résumé de mes tâches en cours",
    "Prépare un point d'avancement client",
    "Aide-moi à terminer ce projet plus rapidement",
    "Supprime les tâches terminées ou obsolètes de mes priorités",
  ],
};

export function suggestionsFor(key: string): string[] {
  return AGENT_SUGGESTIONS[key] ?? [];
}
