export type AgentMeta = {
  key: string;
  name: string;
  role: string;
  description: string;
  mission: string;
  emoji: string;
  ring: string;
  chip: string;
  primary?: boolean;
  skills: string[];
};

export const AGENTS: AgentMeta[] = [
  {
    key: "directeur",
    name: "Éric",
    role: "Directeur IA",
    description:
      "Orchestrateur de l'entreprise : il comprend votre demande, analyse le contexte et distribue les tâches aux autres agents.",
    mission: "Piloter toute l'équipe",
    emoji: "🧭",
    ring: "bg-amber-100 text-amber-900 ring-amber-200",
    chip: "bg-amber-50 text-amber-800",
    primary: true,
    skills: [
      "compréhension de la demande",
      "analyse du contexte",
      "distribution des tâches",
      "coordination des 9 agents",
      "suivi de bout en bout",
    ],
  },
  {
    key: "commercial",
    name: "Jason",
    role: "Commercial",
    description: "Prospection et ventes : il trouve, qualifie et convertit vos futurs clients.",
    mission: "Trouver et convertir",
    emoji: "🤝",
    ring: "bg-sky-100 text-sky-900 ring-sky-200",
    chip: "bg-sky-50 text-sky-800",
    skills: [
      "génération de prospects",
      "persona",
      "qualification",
      "scoring",
      "enrichissement",
      "personnalisation",
      "campagnes",
      "suivi commercial",
      "opportunités",
      "conversion",
      "analyse commerciale",
    ],
  },
  {
    key: "devis",
    name: "Michael",
    role: "Devis",
    description: "Devis et paiements : de l'analyse du besoin jusqu'à la facture réglée.",
    mission: "Devis & encaissement",
    emoji: "🧾",
    ring: "bg-violet-100 text-violet-900 ring-violet-200",
    chip: "bg-violet-50 text-violet-800",
    skills: [
      "analyse des besoins",
      "création de devis",
      "catalogue",
      "remises",
      "TVA",
      "envoi",
      "relances",
      "paiement",
      "acomptes",
      "factures",
      "transformation devis → projet",
    ],
  },
  {
    key: "clients",
    name: "Jennifer",
    role: "Clients",
    description: "Clients et relation : CRM, fiche 360° et satisfaction au quotidien.",
    mission: "Garder les clients",
    emoji: "💬",
    ring: "bg-emerald-100 text-emerald-900 ring-emerald-200",
    chip: "bg-emerald-50 text-emerald-800",
    skills: [
      "CRM",
      "fiche client 360°",
      "historique",
      "demandes",
      "échanges",
      "suivi",
      "satisfaction",
      "espace client",
      "opportunités futures",
    ],
  },
  {
    key: "relances",
    name: "Clara",
    role: "Relances",
    description: "Relances et suivi : elle n'oublie jamais un devis ou une facture en attente.",
    mission: "Ne rien laisser filer",
    emoji: "⏰",
    ring: "bg-orange-100 text-orange-900 ring-orange-200",
    chip: "bg-orange-50 text-orange-800",
    skills: [
      "relances devis",
      "relances paiement",
      "relances prospects",
      "emails",
      "séquences",
      "rappels",
      "suivi des réponses",
    ],
  },
  {
    key: "marketing",
    name: "Lamine",
    role: "Marketing",
    description: "Marketing et contenu : promesses, campagnes, sites et SEO.",
    mission: "Se faire connaître",
    emoji: "📣",
    ring: "bg-rose-100 text-rose-900 ring-rose-200",
    chip: "bg-rose-50 text-rose-800",
    skills: [
      "promesses",
      "propositions de valeur",
      "contenu",
      "campagnes",
      "email marketing",
      "stratégie",
      "landing pages",
      "sites web",
      "SEO",
      "GEO",
      "funnel",
    ],
  },
  {
    key: "rh",
    name: "Mariéme",
    role: "Ressources humaines",
    description: "Recrutement et RH : offres, CV, entretiens et vivier de talents.",
    mission: "Recruter mieux",
    emoji: "👥",
    ring: "bg-indigo-100 text-indigo-900 ring-indigo-200",
    chip: "bg-indigo-50 text-indigo-800",
    skills: [
      "offres",
      "CV",
      "lettres",
      "scoring",
      "candidats",
      "entretiens",
      "analyse audio",
      "suivi",
      "décision assistée",
      "vivier",
    ],
  },
  {
    key: "gestion",
    name: "Audrey",
    role: "Gestion",
    description: "Finance et administratif : factures, TVA, dépenses et reporting.",
    mission: "Tenir les comptes",
    emoji: "📁",
    ring: "bg-teal-100 text-teal-900 ring-teal-200",
    chip: "bg-teal-50 text-teal-800",
    skills: [
      "factures",
      "paiements",
      "TVA",
      "dépenses",
      "documents",
      "suivi financier",
      "reporting",
      "administratif",
    ],
  },
  {
    key: "analyse",
    name: "Ethan",
    role: "Analyse",
    description: "Analyse et veille : marché, concurrence, e-réputation et recommandations.",
    mission: "Garder une longueur d'avance",
    emoji: "📊",
    ring: "bg-cyan-100 text-cyan-900 ring-cyan-200",
    chip: "bg-cyan-50 text-cyan-800",
    skills: [
      "analyse business",
      "étude de marché",
      "analyse sectorielle",
      "analyse concurrentielle",
      "veille",
      "e-réputation",
      "recherches web",
      "recommandations",
    ],
  },
  {
    key: "projets",
    name: "Chloé",
    role: "Projets",
    description: "Projets et production : étapes, tâches, échéances et livraison.",
    mission: "Livrer sans stress",
    emoji: "🗂️",
    ring: "bg-lime-100 text-lime-900 ring-lime-200",
    chip: "bg-lime-50 text-lime-800",
    skills: [
      "création de projets",
      "étapes",
      "tâches",
      "équipe",
      "documents",
      "demandes client",
      "échéances",
      "avancement",
      "livraison",
      "finalisation",
    ],
  },
];

export const LEAD_AGENT = AGENTS[0] as AgentMeta;

export const agentByKey = (key: string): AgentMeta => AGENTS.find((a) => a.key === key) ?? LEAD_AGENT;
