/** Catalogue central des coûts en crédits IA (source de vérité unique). */
export type CreditAction = { key: string; label: string; cost: number; group: string };

const A = (group: string, list: [string, string, number][]): CreditAction[] =>
  list.map(([key, label, cost]) => ({ key, label, cost, group }));

export const CREDIT_ACTIONS: CreditAction[] = [
  ...A("Images", [
    ["image.premium", "Génération d'une image premium", 2],
    ["image.carousel_2", "Carrousel de 2 images premium", 3],
    ["image.carousel_3", "Carrousel de 3 images premium", 3],
    ["image.carousel_4", "Carrousel de 4 images premium", 3],
    ["image.edit", "Image avec modification IA", 2],
    ["image.variant", "Variante d'image", 2],
    ["image.upscale", "Amélioration / upscale d'une image", 2],
    ["image.remove_object", "Suppression / remplacement d'un élément", 2],
  ]),
  ...A("Vidéos", [
    ["video.premium", "Génération d'une vidéo premium", 5],
    ["video.variant", "Variante vidéo", 5],
    ["video.edit", "Modification d'une vidéo avec IA", 5],
    ["video.promo", "Courte vidéo promotionnelle", 5],
    ["video.ad", "Vidéo publicitaire", 5],
    ["video.social", "Vidéo pour réseaux sociaux", 5],
  ]),
  ...A("Textes courts", [
    ["text.short_answer", "Réponse IA courte", 1],
    ["text.idea", "Génération d'une idée", 1],
    ["text.hook", "Génération d'une accroche", 1],
    ["text.cta", "Génération d'un CTA", 1],
    ["text.slogan", "Génération d'un slogan", 1],
    ["text.promise", "Génération d'une promesse", 1],
    ["text.value_prop", "Proposition de valeur", 1],
    ["text.rewrite", "Réécriture d'un texte", 1],
    ["text.improve", "Correction / amélioration d'un texte", 1],
    ["text.summary", "Résumé court", 1],
    ["text.email_subject", "Objet d'email", 1],
  ]),
  ...A("Emails", [
    ["email.generate", "Génération d'un email", 1],
    ["email.followup", "Relance email", 1],
    ["email.personalize", "Personnalisation d'un email", 1],
    ["email.analyze", "Analyse d'un email", 1],
    ["email.summary", "Résumé d'un email", 1],
    ["email.sequence_simple", "Séquence email simple", 3],
    ["email.sequence_full", "Séquence email complète", 5],
  ]),
  ...A("Prospection", [
    ["prospect.persona", "Génération d'un persona", 1],
    ["prospect.web_search", "Recherche web simple", 1],
    ["prospect.company_search", "Recherche d'entreprises", 1],
    ["prospect.generate", "Génération de prospects", 2],
    ["prospect.generate_25", "Génération de 1 à 25 prospects", 2],
    ["prospect.generate_50", "Génération de 26 à 50 prospects", 4],
    ["prospect.generate_100", "Génération de 51 à 100 prospects", 6],
    ["prospect.enrich", "Enrichissement de prospects", 2],
    ["prospect.qualify", "Qualification de prospects", 1],
    ["prospect.score", "Scoring de prospects", 1],
    ["prospect.analyze", "Analyse d'un prospect", 1],
    ["prospect.personalize", "Personnalisation commerciale", 2],
    ["prospect.angle", "Angle commercial", 1],
    ["prospect.message", "Message de prospection", 1],
    ["prospect.company_analysis", "Analyse d'une entreprise prospect", 2],
  ]),
  ...A("Analyse et veille", [
    ["analysis.simple", "Analyse simple", 1],
    ["analysis.business", "Analyse business", 2],
    ["analysis.competitive", "Analyse concurrentielle", 3],
    ["analysis.competitor_deep", "Analyse approfondie d'un concurrent", 4],
    ["analysis.market_study", "Étude de marché", 4],
    ["analysis.sector", "Analyse sectorielle", 3],
    ["analysis.business_plan", "Business plan", 5],
    ["analysis.opportunities", "Analyse des opportunités", 2],
    ["analysis.risks", "Analyse des risques", 2],
    ["analysis.reco", "Recommandations stratégiques", 2],
    ["watch.web", "Veille web", 2],
    ["watch.competitive", "Veille concurrentielle", 3],
    ["watch.refresh", "Actualisation d'une veille", 2],
    ["watch.briefing", "Briefing de veille", 3],
    ["watch.news", "Analyse d'une actualité", 1],
    ["watch.trend", "Analyse d'une tendance", 2],
  ]),
  ...A("E-réputation", [
    ["rep.mentions", "Recherche de mentions", 2],
    ["rep.analysis", "Analyse d'e-réputation", 3],
    ["rep.analysis_deep", "Analyse approfondie d'e-réputation", 5],
    ["rep.review_analysis", "Analyse d'un avis", 1],
    ["rep.review_reply", "Réponse à un avis", 1],
    ["rep.sentiment", "Analyse du sentiment", 1],
    ["rep.reviews_summary", "Synthèse des avis", 2],
  ]),
  ...A("Réunions / audio / vidéo", [
    ["meeting.transcribe_audio", "Transcription audio", 2],
    ["meeting.transcribe", "Transcription d'une réunion", 2],
    ["meeting.summary", "Résumé d'une réunion", 1],
    ["meeting.analysis", "Analyse d'une réunion", 2],
    ["meeting.needs", "Extraction des besoins client", 2],
    ["meeting.audio_analysis", "Analyse d'un fichier audio", 2],
    ["meeting.video_analysis", "Analyse d'un fichier vidéo", 3],
    ["meeting.to_quote", "Analyse réunion → préparation devis", 4],
  ]),
  ...A("Devis", [
    ["quote.generate", "Génération d'un devis avec l'IA", 2],
    ["quote.from_meeting", "Devis à partir d'une réunion", 4],
    ["quote.needs_analysis", "Analyse des besoins pour un devis", 2],
    ["quote.catalog_match", "Correspondance besoins → catalogue", 1],
    ["quote.analyze", "Analyse d'un devis", 1],
    ["quote.followup", "Relance de devis", 1],
  ]),
  ...A("Marketing", [
    ["mkt.promise", "Génération d'une promesse", 1],
    ["mkt.value_prop", "Proposition de valeur", 1],
    ["mkt.value_prop_optimize", "Optimisation d'une proposition de valeur", 1],
    ["mkt.competitor_props", "Analyse des propositions concurrentes", 2],
    ["mkt.strategy", "Stratégie marketing", 2],
    ["mkt.campaign", "Campagne marketing", 3],
    ["mkt.funnel", "Génération d'un funnel", 2],
    ["mkt.landing", "Landing page", 3],
    ["mkt.site_brief", "Briefing de site", 2],
    ["mkt.page_content", "Contenu d'une page", 2],
    ["mkt.site_content", "Contenu complet d'un site", 8],
    ["mkt.seo", "Génération SEO d'une page", 2],
    ["mkt.geo", "Génération GEO d'une page", 2],
    ["mkt.image_prompts", "Prompts images", 1],
    ["mkt.icon_prompts", "Prompts icônes", 1],
  ]),
  ...A("RH", [
    ["hr.job_analysis", "Analyse d'une offre d'emploi", 2],
    ["hr.cv_analysis", "Analyse d'un CV", 2],
    ["hr.letter_analysis", "Analyse d'une lettre de motivation", 1],
    ["hr.candidate_score", "Scoring d'un candidat", 2],
    ["hr.candidates_compare", "Comparaison de candidats", 3],
    ["hr.interview_transcribe", "Transcription d'un entretien", 2],
    ["hr.interview_audio", "Analyse d'un entretien audio", 3],
    ["hr.interview_summary", "Résumé d'un entretien", 1],
    ["hr.interview_questions", "Questions d'entretien", 1],
    ["hr.job_offer", "Génération d'une offre d'emploi", 2],
    ["hr.candidate_reco", "Recommandation candidat", 2],
  ]),
  ...A("Documents", [
    ["doc.summary", "Résumé d'un document", 1],
    ["doc.analysis", "Analyse d'un document", 2],
    ["doc.extract", "Extraction d'informations", 1],
    ["doc.create_simple", "Création d'un document simple", 2],
    ["doc.create_pro", "Document professionnel complet", 3],
    ["doc.report", "Rapport complet", 4],
    ["doc.multi_analysis", "Analyse de plusieurs documents", 3],
  ]),
  ...A("Éric — Orchestrateur", [
    ["eric.chat", "Conversation simple avec Éric", 0],
    ["eric.answer", "Question nécessitant une réponse IA", 1],
    ["eric.analyze_request", "Analyse d'une demande complexe", 1],
    ["eric.task_run", "Exécution d'une tâche par un agent", 1],
    ["agent.direct_message", "Demande directe à un agent", 1],

  ]),
];

export const CREDIT_MAP: Record<string, CreditAction> = Object.fromEntries(
  CREDIT_ACTIONS.map((a) => [a.key, a]),
);

export const creditAction = (key: string): CreditAction =>
  CREDIT_MAP[key] ?? { key, label: key, cost: 1, group: "Autre" };

export const creditCost = (key: string): number => creditAction(key).cost;

export const creditLabel = (n: number) => `${n} crédit${n > 1 ? "s" : ""}`;
