/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAideRouteImport } from './routes/_authenticated/aide'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAutomatisationsRouteImport } from './routes/_authenticated/automatisations'
import { Route as AuthenticatedBienvenueRouteImport } from './routes/_authenticated/bienvenue'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedEntrepriseRouteImport } from './routes/_authenticated/entreprise'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEricRouteImport } from './routes/_authenticated/eric'
import { Route as AuthenticatedJasonRouteImport } from './routes/_authenticated/jason'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedProjetsRouteImport } from './routes/_authenticated/projets'
import { Route as AuthenticatedProspectsRouteImport } from './routes/_authenticated/prospects'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as PayerTokenRouteImport } from './routes/payer.$token'
import { Route as AuthenticatedDevisIndexRouteImport } from './routes/_authenticated/devis.index'
import { Route as AuthenticatedDevisIdRouteImport } from './routes/_authenticated/devis.$id'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAideRoute = AuthenticatedAideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomatisationsRoute =
  AuthenticatedAutomatisationsRouteImport.update({
    id: '/automatisations',
    path: '/automatisations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBienvenueRoute = AuthenticatedBienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrepriseRoute = AuthenticatedEntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEricRoute = AuthenticatedEricRouteImport.update({
  id: '/eric',
  path: '/eric',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJasonRoute = AuthenticatedJasonRouteImport.update({
  id: '/jason',
  path: '/jason',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetsRoute = AuthenticatedProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProspectsRoute = AuthenticatedProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PayerTokenRoute = PayerTokenRouteImport.update({
  id: '/payer/$token',
  path: '/payer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevisIndexRoute = AuthenticatedDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevisIdRoute = AuthenticatedDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aide': typeof AuthenticatedAideRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automatisations': typeof AuthenticatedAutomatisationsRoute
  '/bienvenue': typeof AuthenticatedBienvenueRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/entreprise': typeof AuthenticatedEntrepriseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/eric': typeof AuthenticatedEricRoute
  '/jason': typeof AuthenticatedJasonRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/prospects': typeof AuthenticatedProspectsRoute
  '/rh': typeof AuthenticatedRhRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/payer/$token': typeof PayerTokenRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/': typeof AuthenticatedDevisIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aide': typeof AuthenticatedAideRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automatisations': typeof AuthenticatedAutomatisationsRoute
  '/bienvenue': typeof AuthenticatedBienvenueRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/entreprise': typeof AuthenticatedEntrepriseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/eric': typeof AuthenticatedEricRoute
  '/jason': typeof AuthenticatedJasonRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/prospects': typeof AuthenticatedProspectsRoute
  '/rh': typeof AuthenticatedRhRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/payer/$token': typeof PayerTokenRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis': typeof AuthenticatedDevisIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aide': typeof AuthenticatedAideRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automatisations': typeof AuthenticatedAutomatisationsRoute
  '/_authenticated/bienvenue': typeof AuthenticatedBienvenueRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/entreprise': typeof AuthenticatedEntrepriseRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/eric': typeof AuthenticatedEricRoute
  '/_authenticated/jason': typeof AuthenticatedJasonRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/projets': typeof AuthenticatedProjetsRoute
  '/_authenticated/prospects': typeof AuthenticatedProspectsRoute
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/payer/$token': typeof PayerTokenRoute
  '/_authenticated/devis/$id': typeof AuthenticatedDevisIdRoute
  '/_authenticated/devis/': typeof AuthenticatedDevisIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aide'
    | '/analytics'
    | '/automatisations'
    | '/bienvenue'
    | '/catalogue'
    | '/clients'
    | '/credits'
    | '/documents'
    | '/emails'
    | '/entreprise'
    | '/equipe'
    | '/eric'
    | '/jason'
    | '/marketing'
    | '/paiements'
    | '/parametres'
    | '/plans'
    | '/projets'
    | '/prospects'
    | '/rh'
    | '/tableau-de-bord'
    | '/payer/$token'
    | '/devis/$id'
    | '/devis/'
    | '/api/public/stripe/webhook'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aide'
    | '/analytics'
    | '/automatisations'
    | '/bienvenue'
    | '/catalogue'
    | '/clients'
    | '/credits'
    | '/documents'
    | '/emails'
    | '/entreprise'
    | '/equipe'
    | '/eric'
    | '/jason'
    | '/marketing'
    | '/paiements'
    | '/parametres'
    | '/plans'
    | '/projets'
    | '/prospects'
    | '/rh'
    | '/tableau-de-bord'
    | '/payer/$token'
    | '/devis/$id'
    | '/devis'
    | '/api/public/stripe/webhook'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aide'
    | '/_authenticated/analytics'
    | '/_authenticated/automatisations'
    | '/_authenticated/bienvenue'
    | '/_authenticated/catalogue'
    | '/_authenticated/clients'
    | '/_authenticated/credits'
    | '/_authenticated/documents'
    | '/_authenticated/emails'
    | '/_authenticated/entreprise'
    | '/_authenticated/equipe'
    | '/_authenticated/eric'
    | '/_authenticated/jason'
    | '/_authenticated/marketing'
    | '/_authenticated/paiements'
    | '/_authenticated/parametres'
    | '/_authenticated/plans'
    | '/_authenticated/projets'
    | '/_authenticated/prospects'
    | '/_authenticated/rh'
    | '/_authenticated/tableau-de-bord'
    | '/payer/$token'
    | '/_authenticated/devis/$id'
    | '/_authenticated/devis/'
    | '/api/public/stripe/webhook'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PayerTokenRoute: typeof PayerTokenRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aide': {
      id: '/_authenticated/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AuthenticatedAideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automatisations': {
      id: '/_authenticated/automatisations'
      path: '/automatisations'
      fullPath: '/automatisations'
      preLoaderRoute: typeof AuthenticatedAutomatisationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bienvenue': {
      id: '/_authenticated/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof AuthenticatedBienvenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise': {
      id: '/_authenticated/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof AuthenticatedEntrepriseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eric': {
      id: '/_authenticated/eric'
      path: '/eric'
      fullPath: '/eric'
      preLoaderRoute: typeof AuthenticatedEricRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jason': {
      id: '/_authenticated/jason'
      path: '/jason'
      fullPath: '/jason'
      preLoaderRoute: typeof AuthenticatedJasonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projets': {
      id: '/_authenticated/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedProjetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospects': {
      id: '/_authenticated/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedProspectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/payer/$token': {
      id: '/payer/$token'
      path: '/payer/$token'
      fullPath: '/payer/$token'
      preLoaderRoute: typeof PayerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/devis/': {
      id: '/_authenticated/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AuthenticatedDevisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis/$id': {
      id: '/_authenticated/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AuthenticatedDevisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAideRoute: typeof AuthenticatedAideRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomatisationsRoute: typeof AuthenticatedAutomatisationsRoute
  AuthenticatedBienvenueRoute: typeof AuthenticatedBienvenueRoute
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedEntrepriseRoute: typeof AuthenticatedEntrepriseRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEricRoute: typeof AuthenticatedEricRoute
  AuthenticatedJasonRoute: typeof AuthenticatedJasonRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProjetsRoute: typeof AuthenticatedProjetsRoute
  AuthenticatedProspectsRoute: typeof AuthenticatedProspectsRoute
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedDevisIdRoute: typeof AuthenticatedDevisIdRoute
  AuthenticatedDevisIndexRoute: typeof AuthenticatedDevisIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAideRoute: AuthenticatedAideRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomatisationsRoute: AuthenticatedAutomatisationsRoute,
  AuthenticatedBienvenueRoute: AuthenticatedBienvenueRoute,
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedEntrepriseRoute: AuthenticatedEntrepriseRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEricRoute: AuthenticatedEricRoute,
  AuthenticatedJasonRoute: AuthenticatedJasonRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProjetsRoute: AuthenticatedProjetsRoute,
  AuthenticatedProspectsRoute: AuthenticatedProspectsRoute,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedDevisIdRoute: AuthenticatedDevisIdRoute,
  AuthenticatedDevisIndexRoute: AuthenticatedDevisIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PayerTokenRoute: PayerTokenRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
